const Kana = {
    "a":   { Hiragana: "あ", Katakana: "ア" },
    "i":   { Hiragana: "い", Katakana: "イ" },
    "u":   { Hiragana: "う", Katakana: "ウ" },
    "e":   { Hiragana: "え", Katakana: "エ" },
    "o":   { Hiragana: "お", Katakana: "オ" },

    "ka":  { Hiragana: "か", Katakana: "カ" },
    "ki":  { Hiragana: "き", Katakana: "キ" },
    "ku":  { Hiragana: "く", Katakana: "ク" },
    "ke":  { Hiragana: "け", Katakana: "ケ" },
    "ko":  { Hiragana: "こ", Katakana: "コ" },

    "ga":  { Hiragana: "が", Katakana: "ガ" },
    "gi":  { Hiragana: "ぎ", Katakana: "ギ" },
    "gu":  { Hiragana: "ぐ", Katakana: "グ" },
    "ge":  { Hiragana: "げ", Katakana: "ゲ" },
    "go":  { Hiragana: "ご", Katakana: "ゴ" },

    "sa":  { Hiragana: "さ", Katakana: "サ" },
    "shi": { Hiragana: "し", Katakana: "シ" },
    "su":  { Hiragana: "す", Katakana: "ス" },
    "se":  { Hiragana: "せ", Katakana: "セ" },
    "so":  { Hiragana: "そ", Katakana: "ソ" },

    "za":  { Hiragana: "ざ", Katakana: "ザ" },
    "ji":  { Hiragana: "じ", Katakana: "ジ" },
    "zu":  { Hiragana: "ず", Katakana: "ズ" },
    "ze":  { Hiragana: "ぜ", Katakana: "ゼ" },
    "zo":  { Hiragana: "ぞ", Katakana: "ゾ" },

    "ta":  { Hiragana: "た", Katakana: "タ" },
    "chi": { Hiragana: "ち", Katakana: "チ" },
    "tsu": { Hiragana: "つ", Katakana: "ツ" },
    "te":  { Hiragana: "て", Katakana: "テ" },
    "to":  { Hiragana: "と", Katakana: "ト" },

    "da":  { Hiragana: "だ", Katakana: "ダ" },
    "dzi": { Hiragana: "ぢ", Katakana: "ヂ" },
    "dzu": { Hiragana: "づ", Katakana: "ヅ" },
    "de":  { Hiragana: "で", Katakana: "デ" },
    "do":  { Hiragana: "ど", Katakana: "ド" },

    "na":  { Hiragana: "な", Katakana: "ナ" },
    "ni":  { Hiragana: "に", Katakana: "ニ" },
    "nu":  { Hiragana: "ぬ", Katakana: "ヌ" },
    "ne":  { Hiragana: "ね", Katakana: "ネ" },
    "no":  { Hiragana: "の", Katakana: "ノ" },

    "ha":  { Hiragana: "は", Katakana: "ハ" },
    "hi":  { Hiragana: "ひ", Katakana: "ヒ" },
    "hu":  { Hiragana: "ふ", Katakana: "フ" },
    "he":  { Hiragana: "へ", Katakana: "ヘ" },
    "ho":  { Hiragana: "ほ", Katakana: "ホ" },

    "ba":  { Hiragana: "ば", Katakana: "バ" },
    "bi":  { Hiragana: "び", Katakana: "ビ" },
    "bu":  { Hiragana: "ぶ", Katakana: "ブ" },
    "be":  { Hiragana: "べ", Katakana: "ベ" },
    "bo":  { Hiragana: "ぼ", Katakana: "ボ" },

    "pa":  { Hiragana: "ぱ", Katakana: "パ" },
    "pi":  { Hiragana: "ぴ", Katakana: "ピ" },
    "pu":  { Hiragana: "ぷ", Katakana: "プ" },
    "pe":  { Hiragana: "ぺ", Katakana: "ペ" },
    "po":  { Hiragana: "ぽ", Katakana: "ポ" },

    "ma":  { Hiragana: "ま", Katakana: "マ" },
    "mi":  { Hiragana: "み", Katakana: "ミ" },
    "mu":  { Hiragana: "む", Katakana: "ム" },
    "me":  { Hiragana: "め", Katakana: "メ" },
    "mo":  { Hiragana: "も", Katakana: "モ" },

    "ya":  { Hiragana: "や", Katakana: "ヤ" },
    "yu":  { Hiragana: "ゆ", Katakana: "ユ" },
    "yo":  { Hiragana: "よ", Katakana: "ヨ" },

    "ra":  { Hiragana: "ら", Katakana: "ラ" },
    "ri":  { Hiragana: "り", Katakana: "リ" },
    "ru":  { Hiragana: "る", Katakana: "ル" },
    "re":  { Hiragana: "れ", Katakana: "レ" },
    "ro":  { Hiragana: "ろ", Katakana: "ロ" },

    "wa":  { Hiragana: "わ", Katakana: "ワ" },
    "wi":  { Hiragana: "ゐ", Katakana: "ヰ" },
    "we":  { Hiragana: "ゑ", Katakana: "ヱ" },
    "wo":  { Hiragana: "を", Katakana: "ヲ" },

    "n":   { Hiragana: "ん", Katakana: "ン" },

    "kya": { Hiragana: "きゃ", Katakana: "キャ" },
    "sha": { Hiragana: "しゃ", Katakana: "シャ" },
    "cha": { Hiragana: "ちゃ", Katakana: "チャ" },
    "nya": { Hiragana: "にゃ", Katakana: "ニャ" },
    "hya": { Hiragana: "ひゃ", Katakana: "ヒャ" },
    "mya": { Hiragana: "みゃ", Katakana: "ミャ" },
    "rya": { Hiragana: "りゃ", Katakana: "リャ" },
    "gya": { Hiragana: "ぎゃ", Katakana: "ギャ" },
    "ja":  { Hiragana: "じゃ", Katakana: "ジャ" },
    "bya": { Hiragana: "びゃ", Katakana: "ビャ" },
    "pya": { Hiragana: "ぴゃ", Katakana: "ピャ" },

    "kyu": { Hiragana: "きゅ", Katakana: "キュ" },
    "shu": { Hiragana: "しゅ", Katakana: "シュ" },
    "chu": { Hiragana: "ちゅ", Katakana: "チュ" },
    "nyu": { Hiragana: "にゅ", Katakana: "ニュ" },
    "hyu": { Hiragana: "ひゅ", Katakana: "ヒュ" },
    "myu": { Hiragana: "みゅ", Katakana: "ミュ" },
    "ryu": { Hiragana: "りゅ", Katakana: "リュ" },
    "gyu": { Hiragana: "ぎゅ", Katakana: "ギュ" },
    "ju":  { Hiragana: "じゅ", Katakana: "ジュ" },
    "byu": { Hiragana: "びゅ", Katakana: "ビュ" },
    "pyu": { Hiragana: "ぴゅ", Katakana: "ピュ" },

    "kyo": { Hiragana: "きょ", Katakana: "キョ" },
    "sho": { Hiragana: "しょ", Katakana: "ショ" },
    "cho": { Hiragana: "ちょ", Katakana: "チョ" },
    "nyo": { Hiragana: "にょ", Katakana: "ニョ" },
    "hyo": { Hiragana: "ひょ", Katakana: "ヒョ" },
    "myo": { Hiragana: "みょ", Katakana: "ミョ" },
    "ryo": { Hiragana: "りょ", Katakana: "リョ" },
    "gyo": { Hiragana: "ぎょ", Katakana: "ギョ" },
    "jo":  { Hiragana: "じょ", Katakana: "ジョ" },
    "byo": { Hiragana: "びょ", Katakana: "ビョ" },
    "pyo": { Hiragana: "ぴょ", Katakana: "ピョ" },

    // Interpunction
    ".":   { Hiragana: "。",   Katakana: "。"  },
    ",":   { Hiragana: "、",   Katakana: "、"  },

    // Special: only used internally
    "small-tsu":  { Hiragana: "っ", Katakana: "ッ" },
    "long-vovel": { Hiragana: "",   Katakana: "ー" }
};
